apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
spec:
  containers:
    - name: jplay-api
      image: node:20-alpine
      ports:
        - containerPort: 5050
        - protocol: TCP
      type: NodePort
